<?php
$me = $this;
$v1 = $me->a1;
$v2 = $me->a2();
$v3 = $me->a3->a4;
$v4 = $me->a5()->a6;
$v5 = $me->a7()->a8();
?>
<div><?php echo $me->a1; ?></div>
<div><?php echo $me->a2(); ?></div>
<div><?php echo $me->a3->a4; ?></div>
<div><?php echo $me->a5()->a6; ?></div>
<div><?php echo $me->a7()->a8(); ?></div>
<div><?= echo $me->a1; ?></div>
<div><?= echo $me->a2(); ?></div>
<div><?= echo $me->a3->a4; ?></div>
<div><?= echo $me->a5()->a6; ?></div>
<div><?= echo $me->a7()->a8(); ?></div>