<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $me
 */
 $me = $this;
?>
<?=$me->doctype()?>
<?php
$content = $me->content;
$vars = $me->vars();
// !d($vars);die();
$_vars = ifNotSet($vars, '_vars_', []);
$module = ifNotSet($_vars, 'module', "");
$controller = ifNotSet($_vars, 'controller', "");
$controller = str_replace("Controller", "", $controller);
$action = ifNotSet($_vars, 'action', "");
$layout = ifNotSet($_vars, 'layout', "");
// !d($layout);die();
$active_menu = isset($me->active_menu) ? $me->active_menu : "";
unset($vars['content']);
?>
<html>

<head>
  <meta charset="utf-8">
  <?=$me->headTitle()->setAutoEscape(false)?>

  <?=$me->headMeta()?>
  <?=$me->headLink([
    'rel' => 'shortcut icon',
    'type' => 'image/vnd.microsoft.icon',
    'href' => $me->basePath() . '/img/favicon.ico']);
?>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="<?=$me->basePath("js-lib/fontawesome/css/all.min.css");?>">
  <!-- Ionicons -->
  <link rel="stylesheet" href="<?=$me->basePath("js-lib/ionicons/docs/css/ionicons.min.css");?>">

  <link rel="stylesheet" href="<?=$me->basePath("js-lib/bootstrap/dist/css/bootstrap.min.css");?>">

  <!-- overlayScrollbars -->
  <link rel="stylesheet"
    href="<?=$me->basePath("vendor/admin_lte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css");?>">

  <link rel="stylesheet" href="<?=$me->basePath("js-lib/wait-me/dist/waitMe.min.css");?>">

  <link href="<?=$me->basePath("vendor/sweet-alert/jquery.sweet-modal.min.css");?>" rel="stylesheet" />
  <link href="<?=$me->basePath("vendor/sweet-alert/sweetalert.css");?>" rel="stylesheet" />
  <!-- Theme style -->
  <link rel="stylesheet" href="<?=$me->basePath("vendor/admin_lte/dist/css/adminlte.min.css");?>">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <style>
  .content-wrapper {
    background: #e6e6e6;
  }
  </style>
  <!-- Style -->
  <?=$me->headLink();?>

  <?php
if (is_file(APP_PATH . DS . 'public' . DS . 'css' . DS . $layout . DS . '_default.css')) {
    ?>
  <link rel="stylesheet" href="<?=$me->basePath("css/" . $layout . "/_default.css?d=" . time());?>">
  <?php
}
?>

  <?php
if (is_file(APP_PATH . DS . 'public' . DS . 'css' . DS . $layout . DS . $module . DS . '_default.css')) {
    ?>
  <link rel="stylesheet" href="<?=$me->basePath("css/" . $layout . "/" . $module . "/_default.css?d=" . time());?>">
  <?php
}
?>

  <?php
if (is_file(APP_PATH . DS . 'public' . DS . 'css' . DS . $layout . DS . $module . DS . $controller . DS . '_default.css')) {
    ?>
  <link rel="stylesheet"
    href="<?=$me->basePath("css/" . $layout . "/" . $module . "/" . $controller . "/_default.css?d=" . time());?>">
  <?php
}
?>

  <?php
if (is_dir(APP_PATH . DS . 'public' . DS . 'css' . DS . $layout . DS . $module . DS . $controller . DS . $action)) {
    foreach (glob(APP_PATH . DS . 'public' . DS . 'css' . DS . $layout . DS . $module . DS . $controller . DS . $action . DS . "*.css") as $filename) {
        $tmp = explode(DS, $filename);
        $fname = $tmp[count($tmp) - 1];
        ?>
  <link rel="stylesheet"
    href="<?=$me->basePath("css/" . $layout . "/" . $module . "/" . $controller . "/" . $action . "/" . $fname . "?d=" . time());?>">
  <?php
}
}
?>

  <?php
if (is_file(APP_PATH . DS . 'public' . DS . 'css' . DS . $layout . DS . $module . DS . $controller . DS . $action . '.css')) {
    ?>
  <link rel="stylesheet"
    href="<?=$me->basePath("css/" . $layout . "/" . $module . "/" . $controller . "/" . $action . ".css?d=" . time());?>">
  <?php
}
?>
  <?=$me->headStyle();?>
  <script>
  let notifModal, notifModalTitle, notifModalContent;
  let errorModal, errorModalTitle, errorModalContent;
  let loadAJAX = window.XMLHttpRequest.prototype.load;
  window.XMLHttpRequest.prototype.load = function(data) {
    console.warn('AJAX LOADED : ', data);
    return loadAJAX.apply(this, arguments);
  };
  let _APP_NAME_ = "<?=_APP_NAME_;?>";
  </script>
</head>

<body class="hold-transition sidebar-mini layout-fixed text-sm accent-navy sidebar-collapse">
  <!-- Site wrapper -->
  <div id="main-wrap" class="wrapper">

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <?=$content?>
        </div>
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
  </div>
  <!-- ./wrapper -->
  <div class="container">
    <div class="modal fade" id="notifModal" role="dialog">
      <div class="modal-dialog modal-sm bg-default">
        <div class="modal-content bg-default text-white">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <h2 id="notifModalTitle" class="text-white"><?=_APP_NAME_;?></h2>
            <div id="notifModalContent"></div>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="errorModal" role="dialog">
      <div class="modal-dialog modal-sm modals-default nk-red">
        <div class="modal-content bg-default text-white">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <h2 id="errorModalTitle" class="text-white"><?=_APP_NAME_;?></h2>
            <div id="errorModalContent"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- jQuery -->
  <script src="<?=$me->basePath("js-lib/jquery/dist/jquery.min.js");?>"></script>
  <script src="<?=$me->basePath("js-lib/jquery-migrate/jquery-migrate.min.js");?>"></script>
  <!-- Bootstrap 4 -->
  <script src="<?=$me->basePath("js-lib/bootstrap/dist/js/bootstrap.bundle.min.js");?>"></script>
  <!-- <script src="<?=$me->basePath("vendor/admin_lte/plugins/bootstrap/js/bootstrap.bundle.min.js");?>"></script> -->
  <!-- overlayScrollbars -->
  <script src="<?=$me->basePath("vendor/admin_lte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js");?>">
  </script>
  <script src="<?=$me->basePath("js-lib/wait-me/dist/waitMe.min.js");?>"></script>
  <script src="<?=$me->basePath("js-lib/numeral/min/numeral.min.js");?>"></script>
  <script src="<?=$me->basePath("js-lib/numeral/min/locales.min.js");?>"></script>
  <script src="<?=$me->basePath("js-lib/moment/min/moment-with-locales.min.js");?>"></script>
  <script src="<?=$me->basePath("js-lib/thenby/thenBy.min.js");?>"></script>
  <script src="<?=$me->basePath("js-lib/datalib/datalib.min.js");?>"></script>

  <script src="<?=$me->basePath("vendor/sweet-alert/jquery.sweet-modal.min.js");?>"></script>
  <script src="<?=$me->basePath("vendor/sweet-alert/sweetalert.min.js");?>"></script>
  <!-- AdminLTE App -->
  <script src="<?=$me->basePath("vendor/admin_lte/dist/js/adminlte.min.js");?>"></script>
  <script src="<?=$me->basePath("js/global.js?t=" . time());?>"></script>
  <script src="<?=$me->basePath("js/him.js?t=" . time());?>"></script>

  <?=$me->headScript()?>

  <?php
if (is_file(APP_PATH . DS . 'public' . DS . 'js' . DS . $layout . DS . '_default.js')) {
    ?>
  <script src="<?=$me->basePath("js/" . $layout . "/_default.js?d=" . time());?>"></script>
  <?php
}
?>

  <?php
if (is_file(APP_PATH . DS . 'public' . DS . 'js' . DS . $layout . DS . $module . DS . '_default.js')) {
    ?>
  <script src="<?=$me->basePath("js/" . $layout . "/" . $module . "/_default.js?d=" . time());?>"></script>
  <?php
}
?>

  <?php
if (is_file(APP_PATH . DS . 'public' . DS . 'js' . DS . $layout . DS . $module . DS . $controller . DS . '_default.js')) {
    ?>
  <script src="<?=$me->basePath("js/" . $layout . "/" . $module . "/" . $controller . "/_default.js?d=" . time());?>">
  </script>
  <?php
}
?>

  <?php
if (is_dir(APP_PATH . DS . 'public' . DS . 'js' . DS . $layout . DS . $module . DS . $controller . DS . $action)) {
    foreach (glob(APP_PATH . DS . 'public' . DS . 'js' . DS . $layout . DS . $module . DS . $controller . DS . $action . DS . "*.js") as $filename) {
        $tmp = explode(DS, $filename);
        $fname = $tmp[count($tmp) - 1];
        ?>
  <script
    src="<?=$me->basePath("js/" . $layout . "/" . $module . "/" . $controller . "/" . $action . "/" . $fname . "?d=" . time());?>">
  </script>
  <?php
}
}
?>

  <?php
// Debug::dump(APP_PATH . DS . 'public' . DS . 'js' . DS . $layout . DS . $module . DS . $controller . DS . $action . '.js');die('qqq');
if (is_file(APP_PATH . DS . 'public' . DS . 'js' . DS . $layout . DS . $module . DS . $controller . DS . $action . '.js')) {
    ?>
  <script
    src="<?=$me->basePath("js/" . $layout . "/" . $module . "/" . $controller . "/" . $action . ".js?d=" . time());?>">
  </script>
  <?php
}
?>
  <?=$me->inlineScript()?>
</body>

</html>