<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $me
 */
 $me = $this;
?>
<?=$me->doctype()?>

<?php
$content = $me->content;
$vars = $me->vars();
// !d($vars);die();
$_vars = ifNotSet($vars, '_vars_', []);
$module = ifNotSet($_vars, 'module', "");
$controller = ifNotSet($_vars, 'controller', "");
$controller = str_replace("Controller", "", $controller);
$action = ifNotSet($_vars, 'action', "");
$layout = ifNotSet($_vars, 'layout', "");
// !d($layout);die();
$active_menu = isset($me->active_menu) ? $me->active_menu : "";
unset($vars['content']);
?>
<html>

<head>
    <meta charset="utf-8">
    <?=$me->headTitle()->setAutoEscape(false)?>

    <?=$me->headMeta()?>
    <?=$me->headLink([
    'rel' => 'shortcut icon',
    'type' => 'image/vnd.microsoft.icon',
    'href' => $me->basePath() . '/img/favicon.ico']); 
?>
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="<?=$me->basePath("js-lib/bootstrap/dist/css/bootstrap.min.css");?>" >
    <link rel="stylesheet" href="<?=$me->basePath("js-lib/bootstrap-select/dist/css/bootstrap-select.css");?>" >
    <!-- Font Awesome CSS-->
    <link rel="stylesheet"
        href="<?=$me->basePath("vendor/dark_admin/vendor/font-awesome/css/font-awesome.min.css");?>">
    <!-- Custom Font Icons CSS-->
    <link rel="stylesheet" href="<?=$me->basePath("vendor/dark_admin/css/font.css");?>">
    <!-- Google fonts - Muli-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli:300,400,700">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="<?=$me->basePath("js-lib/wait-me/dist/waitMe.min.css");?>">
    <link rel="stylesheet" href="<?=$me->basePath("vendor/dark_admin/css/style.default.css");?>"
        id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="<?=$me->basePath("vendor/dark_admin/css/custom.css?d=" . time());?>">
    <!-- Tweaks for older IEs-->
    <!--[if lt IE 9]>
    <script src="<?=$me->basePath("js-lib/html5shiv/html5shiv.min.js");?>"></script>
    <script src="<?=$me->basePath("js-lib/respond/respond.min.js");?>"></script><![endif]-->

    <?=$me->headLink();?>

<?php
if (is_file(APP_PATH . DS . 'public' . DS . 'css' . DS . $layout . DS . '_default.css')) {
    ?>
<link rel="stylesheet" href="<?=$me->basePath("css/" . $layout . "/_default.css?d=" . time());?>">
<?php
}
?>

<?php
if (is_file(APP_PATH . DS . 'public' . DS . 'css' . DS . $layout . DS . $module . DS . '_default.css')) {
    ?>
<link rel="stylesheet" href="<?=$me->basePath("css/" . $layout . "/" . $module . "/_default.css?d=" . time());?>">
<?php
}
?>

<?php
if (is_file(APP_PATH . DS . 'public' . DS . 'css' . DS . $layout . DS . $module . DS . $controller . DS . '_default.css')) {
    ?>
<link rel="stylesheet" href="<?=$me->basePath("css/" . $layout . "/" . $module . "/" . $controller . "/_default.css?d=" . time());?>">
<?php
}
?>

<?php
if (is_dir(APP_PATH . DS . 'public' . DS . 'css' . DS . $layout . DS . $module . DS . $controller . DS . $action)) {
    foreach (glob(APP_PATH . DS . 'public' . DS . 'css' . DS . $layout . DS . $module . DS . $controller . DS . $action.DS."*.css") as $filename) {
        $tmp = explode(DS,$filename);
        $fname = $tmp[count($tmp)-1];
?>
<link rel="stylesheet" href="<?=$me->basePath("css/" . $layout . "/" . $module . "/" . $controller . "/" . $action . "/".$fname."?d=" . time()); ?>">
<?php
    }
}
?>

<?php
if (is_file(APP_PATH . DS . 'public' . DS . 'css' . DS . $layout . DS . $module . DS . $controller . DS . $action . '.css')) {
    ?>
<link rel="stylesheet" href="<?=$me->basePath("css/" . $layout . "/" . $module . "/" . $controller . "/" . $action . ".css?d=" . time());?>">
<?php
}
?>
    <?=$me->headStyle();?>
    <script>
        let notifModal,notifModalTitle,notifModalContent;
        let errorModal,errorModalTitle,errorModalContent;
        let loadAJAX = window.XMLHttpRequest.prototype.load;
        window.XMLHttpRequest.prototype.load = function(data){
            console.warn('AJAX LOADED : ', data);
            return loadAJAX.apply(this, arguments);
        };
        let _APP_NAME_ = "<?= _APP_NAME_; ?>";
    </script>
</head>
<body>
    <div id="spinner" class="d-none">
        <div class="content">
            <div class="lds-ring">
                <div></div>
                <div></div>
                <div></div>
            </div>
            <h4 id="spinnerText">PLEASE WAIT</h4>
        </div>
    </div>
    <header class="header">
        <?=$me->partial('dark_admin/navbar.phtml', [
    'vars' => $vars,
]);?>
    </header>
    <div class="d-flex align-items-stretch">
        <!-- Sidebar Navigation-->
        <nav id="sidebar">
            <?=$me->partial('dark_admin/sidebar.phtml', [
    'vars' => $vars,
]);?>
        </nav>
        <!-- Sidebar Navigation end-->
        <div class="page-content">
            <?=$me->partial('dark_admin/header.phtml', [
    'vars' => $vars,
]);?>
            <?php
$flashMessenger = $me->flashMessenger();
$flashMessenger->setMessageOpenFormat('<section><div class="container-fluid" id="alert-container"><div class="alert-list"><div %s role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"><i class="notika-icon notika-close"></i></span></button>')
    ->setMessageSeparatorString('</div><div %s role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"><i class="notika-icon notika-close"></i></span></button>')
    ->setMessageCloseString('</div></div></div></section>');
// !d($flashMessenger);
echo $flashMessenger->render('default', ['alert', 'alert-dismissible', 'bg-default']);
echo $flashMessenger->render('error', ['alert', 'alert-dismissible', 'alert-danger']);
echo $flashMessenger->render('info', ['alert', 'alert-dismissible', 'alert-info']);
echo $flashMessenger->render('warning', ['alert', 'alert-dismissible', 'alert-warning']);
echo $flashMessenger->render('success', ['alert', 'alert-dismissible', 'alert-success']);
?>
            <?=$content?>
            <footer class="footer">
                <?=$me->partial('dark_admin/footer.phtml', [
    'vars' => $vars,
]);?>
            </footer>
        </div>
    </div>
    <div class="container">
        <div class="modal fade" id="notifModal" role="dialog">
            <div class="modal-dialog modal-sm bg-default">
                <div class="modal-content bg-default text-white">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <h2 id="notifModalTitle" class="text-white"><?=_APP_NAME_;?></h2>
                        <div id="notifModalContent"></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="errorModal" role="dialog">
            <div class="modal-dialog modal-sm modals-default nk-red">
                <div class="modal-content bg-default text-white">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <h2 id="errorModalTitle" class="text-white"><?=_APP_NAME_;?></h2>
                        <div id="errorModalContent"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- JavaScript files-->
    <script src="<?=$me->basePath("js-lib/jquery/dist/jquery.min.js");?>"></script>
    <script src="<?=$me->basePath("js-lib/jquery-migrate/jquery-migrate.min.js");?>"></script>
    <script src="<?=$me->basePath("vendor/dark_admin/vendor/popper.js/umd/popper.min.js");?>"></script>
    <script src="<?=$me->basePath("js-lib/bootstrap/dist/js/bootstrap.bundle.min.js");?>"></script>
    <script src="<?=$me->basePath("js-lib/bootstrap-select/dist/js/bootstrap-select.js");?>"></script>
    <script src="<?=$me->basePath("js-lib/jquery.cookie/jquery.cookie.js");?>"> </script>
    <script src="<?=$me->basePath("js-lib/chart.js/dist/Chart.bundle.js");?>"></script>
    <script src="<?=$me->basePath("js-lib/autosize/dist/autosize.js");?>"></script>
    <script src="<?=$me->basePath("js-lib/wait-me/dist/waitMe.min.js");?>"></script>
    <script src="<?=$me->basePath("js-lib/numeral/min/numeral.min.js");?>"></script>
    <script src="<?=$me->basePath("js-lib/numeral/min/locales.min.js");?>"></script>
    <script src="<?=$me->basePath("js-lib/moment/min/moment-with-locales.min.js");?>"></script>
    <script src="<?=$me->basePath("js-lib/jquery-validation/dist/jquery.validate.min.js");?>"></script>
    <script src="<?=$me->basePath("vendor/dark_admin/js/front.js");?>"></script>

    <script src="<?=$me->basePath("js-lib/thenby/thenBy.min.js");?>"></script>
    <script src="<?=$me->basePath("js-lib/datalib/datalib.min.js");?>"></script>
    <script src="<?=$me->basePath("js/global.js?t=" . time());?>"></script>
    <script src="<?=$me->basePath("js/him.js?t=" . time());?>"></script>

    <?=$me->headScript()?>

<?php
if (is_file(APP_PATH . DS . 'public' . DS . 'js' . DS . $layout . DS . '_default.js')) {
    ?>
    <script src="<?=$me->basePath("js/" . $layout . "/_default.js?d=" . time());?>"></script>
<?php
}
?>

<?php
if (is_file(APP_PATH . DS . 'public' . DS . 'js' . DS . $layout . DS . $module . DS . '_default.js')) {
    ?>
    <script src="<?=$me->basePath("js/" . $layout . "/" . $module . "/_default.js?d=" . time());?>"></script>
<?php
}
?>

<?php
if (is_file(APP_PATH . DS . 'public' . DS . 'js' . DS . $layout . DS . $module . DS . $controller . DS . '_default.js')) {
    ?>
    <script src="<?=$me->basePath("js/" . $layout . "/" . $module . "/" . $controller . "/_default.js?d=" . time());?>"></script>
<?php
}
?>

<?php
if (is_dir(APP_PATH . DS . 'public' . DS . 'js' . DS . $layout . DS . $module . DS . $controller . DS . $action)) {
    foreach (glob(APP_PATH . DS . 'public' . DS . 'js' . DS . $layout . DS . $module . DS . $controller . DS . $action.DS."*.js") as $filename) {
        $tmp = explode(DS,$filename);
        $fname = $tmp[count($tmp)-1];
?>
<script src="<?=$me->basePath("js/" . $layout . "/" . $module . "/" . $controller . "/" . $action . "/".$fname."?d=" . time());?>"></script>
<?php
    }
}
?>

<?php
// Debug::dump(APP_PATH . DS . 'public' . DS . 'js' . DS . $layout . DS . $module . DS . $controller . DS . $action . '.js');die('qqq');
if (is_file(APP_PATH . DS . 'public' . DS . 'js' . DS . $layout . DS . $module . DS . $controller . DS . $action . '.js')) {
    ?>
    <script src="<?=$me->basePath("js/" . $layout . "/" . $module . "/" . $controller . "/" . $action . ".js?d=" . time());?>"></script>
<?php
}
?>
    <?=$me->inlineScript()?>
</body>

</html>