<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $me
 */
 $me = $this;
?>
<?php
$_vars = $me->vars['_vars_'];
// !d($vars);die();
$_routeparam = $_vars['route_param'];
?>
<nav class="main-header navbar navbar-expand navbar-dark navbar-navy text-sm">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <!-- <li class="nav-item d-none d-sm-inline-block">
            <a href="../../index3.html" class="nav-link">Home</a>
        </li> -->
    <!--<li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
        </li> -->
  </ul>

  <!-- SEARCH FORM -->
  <!-- <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search"
                aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form> -->

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Messages Dropdown Menu -->
    <?php /*echo $me->partial('admin_lte/navbar-msg.phtml',[
'vars'=>$me->vars
]); */?>

    <!-- Notifications Dropdown Menu -->
    <?php /*echo $me->partial('admin_lte/navbar-notif.phtml',[
    'vars'=>$me->vars
    ]);*/?>
  <!-- Counter -->
  <?php echo $me->partial('admin_lte/navbar-counter.phtml',[
  'vars'=>$me->vars
]);?>

    <li class="nav-item">
      <a class="nav-link" href="<?=$me->url(strtolower($_vars['module']) . "/auth/logout");?>" role="button">
        <i class="fas fa-sign-out-alt"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
        <i class="fas fa-th-large"></i>
      </a>
    </li>
  </ul>
</nav>