<footer class="main-footer text-sm">
    <div class="float-right d-none d-sm-block">
        template by <a href="https://adminlte.io" class="font-weight-bold">AdminLTE.io</a>
    </div>
    <strong>Copyright <?= _COPY_YEAR_; ?><?= ((int) date("Y") > _COPY_YEAR_) ? "-" . date("Y") : "";?>
    <a href="<?= _COPY_LINK_; ?>" class="font-weight-bold text-danger" style="color:rgba(213,19,3,1) !important;"><?= _COPY_OWNER_; ?></a>.</strong> All rights reserved.
</footer>