<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $me
 */
 $me = $this;
?>
<?php
$_vars = $me->vars['_vars_'];
// !d($_vars['node']);
?>
<div class="rightbar-parent"><div class="rightbar-child">
    <div class="card card-default">
        <div class="card-header bg-navy">
            <h3 class="card-title">
                <i class="fas fa-server"></i>
                ENTERPRISE NODE
            </h3>
        </div>
        <!-- /.card-header bg-navy -->
        <div class="card-body border-navy">
            <div class="d-flex flex-wrap justify-content-center">
                <?php
            foreach ($_vars['node']['enterprise'] as $k=>$v) {
                ?>
                <div class="info-box node-box" id="node-box-enterprise-<?= $k; ?>" data-id="<?= $k; ?>" data-group="enterprise"
                    data-ip="<?= $v['ip_addr']; ?>">
                    <span class="info-box-icon bg-danger main-stat"><i
                            class="fas fa-arrow-circle-down"></i></span>
                    <div class="info-box-content m-auto">
                        <span class="info-box-text server"><?= $v['name']; ?></span>
                        <span class="info-box-number server"><?= $v['ip_addr']; ?></span>
                    </div>
                    <div class="info-box-conten d-flex flex-column ">
                        <div class="badge flex-fill bg-danger text-center border border-white">
                            <div class="mt-1 ping-stat">PING</div>
                        </div>
                        <div class="badge flex-fill bg-danger text-center border border-white">
                            <div class="mt-1 api-stat">API</div>
                        </div>
                    </div>
                </div>
                <?php
            }
            ?>
            </div>
        </div>
    </div>
    <div class="card card-default">
        <div class="card-header bg-navy">
            <h3 class="card-title">
                <i class="fas fa-server"></i>
                RETAIL NODE
            </h3>
        </div>
        <!-- /.card-header bg-navy -->
        <div class="card-body">
            <div class="d-flex flex-wrap justify-content-center">
                <?php
            foreach ($_vars['node']['retail'] as $k=>$v) {
                ?>
                <div class="info-box node-box" id="node-box-retail-<?= $k; ?>" data-id="<?= $k; ?>" data-group="retail"
                    data-ip="<?= $v['ip_addr']; ?>">
                    <span class="info-box-icon bg-danger main-stat"><i
                            class="fas fa-arrow-circle-down"></i></span>
                    <div class="info-box-content m-auto">
                        <span class="info-box-text server"><?= $v['name']; ?></span>
                        <span class="info-box-number server"><?= $v['ip_addr']; ?></span>
                    </div>
                    <div class="info-box-conten d-flex flex-column ">
                        <div class="badge flex-fill bg-danger text-center border border-white">
                            <div class="mt-1 ping-stat">PING</div>
                        </div>
                        <div class="badge flex-fill bg-danger text-center border border-white">
                            <div class="mt-1 api-stat">API</div>
                        </div>
                    </div>
                </div>
                <?php
            }
            ?>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
</div></div>