<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $me
 */
 $me = $this;
?>
<style>
.breadcrumb li a {
    color: white !important;
}
.breadcrumb li.active a {
    font-weight: bold;
    color: #DB6574 !important;
}
</style>
<?php
// !d($me->vars);
$_vars = $me->vars['_vars_'];
//!d($vars);
$_routeparam = $_vars['route_param'];

$showtitle = $_vars['show_title'] ?? false;
if(!$showtitle)$showtitle = $_routeparam['show_title'] ?? false;
$title = $_vars['title'] ?? "";
if($title==="")$title = $_routeparam['title'] ?? "";

$showbreadcrumb = $_vars['show_breadcrumb'] ?? false;
$breadcrumb = $_vars['breadcrumb'] ?? [];
//!d($breadcrumb);
if($showtitle || $showbreadcrumb){
?>
    <div class="page-header">
        <div class="container-fluid">
            <?php
            if($showtitle){
            ?>
                <div class="d-inline-block text-left">
                    <h2 class="h5 no-margin-bottom text-danger"><?= $title; ?></h2>
                </div>
            <?php
            }
            ?>
            <div class="pull-right text-right d-none d-md-block">
                <?php
                if($showbreadcrumb){
                ?>
                    <ol class="breadcrumb p-0">
                        <?php
                        foreach($breadcrumb as $v){
                            $class = $v['class'] ?? [];
                            $link = $v['link'] ?? "#";
                            $label = $v['label'] ?? "";
//                            !d($v);
                        ?>
                            <li class="breadcrumb-item <?= implode(" ",$class); ?>"><a href="<?= $link; ?>"><?= $label; ?></a></li>
                        <?php
                        }
                        ?>
                    </ol>
                <?php
                }
                ?>
            </div>
        </div>
    </div>
<?php
}else{
    echo '<div class="mb-3"></div>';
}
?>

