<a id="navbarDropdownMenuLink2" href="#"
   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
   class="nav-link tasks-toggle">
    <i class="icon-new-file"></i>
    <span class="badge dashbg-3">9</span>
</a>
<div aria-labelledby="navbarDropdownMenuLink2" class="dropdown-menu tasks-list">
    <a href="#"
       class="dropdown-item">
        <div class="text d-flex justify-content-between">
            <strong>Task 1</strong><span>40% complete</span>
        </div>
        <div class="progress">
            <div role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0"
                 aria-valuemax="100" class="progress-bar dashbg-1"></div>
        </div>
    </a>
    <a href="#" class="dropdown-item">
        <div class="text d-flex justify-content-between">
            <strong>Task 2</strong><span>20% complete</span></div>
        <div class="progress">
            <div role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0"
                 aria-valuemax="100" class="progress-bar dashbg-3"></div>
        </div>
    </a>
    <a href="#" class="dropdown-item">
        <div class="text d-flex justify-content-between">
            <strong>Task 3</strong><span>70% complete</span></div>
        <div class="progress">
            <div role="progressbar" style="width: 70%" aria-valuenow="70" aria-valuemin="0"
                 aria-valuemax="100" class="progress-bar dashbg-2"></div>
        </div>
    </a>
    <a href="#" class="dropdown-item">
        <div class="text d-flex justify-content-between">
            <strong>Task 4</strong><span>30% complete</span>
        </div>
        <div class="progress">
            <div role="progressbar" style="width: 30%" aria-valuenow="30" aria-valuemin="0"
                 aria-valuemax="100" class="progress-bar dashbg-4"></div>
        </div>
    </a>
    <a href="#" class="dropdown-item">
        <div class="text d-flex justify-content-between">
            <strong>Task 5</strong><span>65% complete</span></div>
        <div class="progress">
            <div role="progressbar" style="width: 65%" aria-valuenow="65" aria-valuemin="0"
                 aria-valuemax="100" class="progress-bar dashbg-1"></div>
        </div>
    </a>
    <a href="#" class="dropdown-item text-center">
        <strong>See All Tasks <i class="fa fa-angle-right"></i></strong>
    </a>
</div>