<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $me
 */
 $me = $this;
?>
<?php
// !d($me->vars);
$title1 = $me->vars['_vars_']['module'] === "App" ? _APP_ALIAS_ : $me->vars['_vars_']['module'];
$route1 = ($me->vars['_vars_']['module'] === "App" || $me->vars['_vars_']['module'] === "Core") ? "landing" : strtolower($me->vars['_vars_']['module']);
$maintitle = ($me->vars['mainTitle']) ?? "";
//!d($title1);
$title2 = substr($title1, 0, 1);
?>
<nav class="navbar navbar-expand-lg p-2">
    <?php
/*
<div class="search-panel">
<?= $me->partial('dark_admin/navbar-searchpanel.phtml',[
'vars'=>$me->vars
]); ?>
</div>
 */
?>
    <div class="container-fluid d-flex align-items-center justify-content-between">
        <div class="navbar-header">
            <!-- Navbar Header-->
            <a href="<?=$me->url($route1);?>" class="navbar-brand">
                <div class="brand-text brand-big visible">
                    <strong class="text-primary"><?=$title1;?></strong> <strong>App</strong>
                </div>
                <div class="brand-text brand-sm">
                    <strong class="text-primary"><?=$title2;?></strong><strong>A</strong>
                </div>
            </a>
            <!-- Sidebar Toggle Btn-->
            <button class="sidebar-toggle"><i class="fa fa-long-arrow-left"></i></button>
        </div>
        <div class="right-menu list-inline no-margin-bottom">
            <div class="mr-3 d-none d-md-inline font-weight-bold"><?=$maintitle;?></div>
            <?php
/*
<div class="list-inline-item">
<a href="#" class="search-open nav-link"><i class="icon-magnifying-glass-browser"></i></a>
</div>
 */
?>
            <!-- Messages-->
            <?php
/*
?>
<div class="list-inline-item dropdown">
<?= $me->partial('dark_admin/navbar-message.phtml',[
'vars'=>$me->vars
]); ?>
</div>
 */
?>
            <!-- Tasks-->
            <?php
/*
<div class="list-inline-item dropdown">
<?= $me->partial('dark_admin/navbar-tasks.phtml',[
'vars'=>$me->vars
]); ?>
</div>
 */
?>
            <!-- Tasks end-->
            <!-- Megamenu-->
            <?php
/*
<div class="list-inline-item dropdown menu-large">
<?= $me->partial('dark_admin/navbar-megamenu.phtml',[
'vars'=>$me->vars
]); ?>
</div>
 */
?>
            <!-- Megamenu end     -->
            <!-- Languages dropdown    -->
            <?php
/*
<div class="list-inline-item dropdown">
<?= $me->partial('dark_admin/navbar-lang.phtml',[
'vars'=>$me->vars
]); ?>
</div>
 */
?>
            <!-- Log out               -->
            <div class="list-inline-item logout">
                <a id="logout" href="<?=$me->url("auth/logout");?>" class="nav-link text-danger">
                    <span class="d-none d-sm-inline">Logout </span><i class="icon-logout"></i>
                </a>
            </div>
    </div>
    </div>
</nav>