<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $me
 */
 $me = $this;
?>
<!--a id="languages" rel="nofollow" data-target="#" href="#"
   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
   class="nav-link language dropdown-toggle">
    <img src="<?= $me->basePath("vendor/dark_admin/img/flags/16/GB.png"); ?>"
         alt="English"><span class="d-none d-sm-inline-block">English</span>
</a>
<div aria-labelledby="languages" class="dropdown-menu">
    <a rel="nofollow" href="#"
       class="dropdown-item">
        <img src="<?= $me->basePath("vendor/dark_admin/img/flags/16/DE.png"); ?>"
             alt="English" class="mr-2"><span>German</span>
    </a>
    <a rel="nofollow" href="#" class="dropdown-item">
        <img src="<?= $me->basePath("vendor/dark_admin/img/flags/16/FR.png"); ?>"
             alt="English" class="mr-2"><span>French </span>
    </a>
</div-->