<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $me
 */
 $me = $this;
?>
<a id="navbarDropdownMenuLink1" href="#"
   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
   class="nav-link messages-toggle"><i class="icon-email"></i>
    <span class="badge dashbg-1">5</span>
</a>
<div aria-labelledby="navbarDropdownMenuLink1" class="dropdown-menu messages">
    <a href="#"
       class="dropdown-item message d-flex align-items-center">
        <div class="profile">
            <!--img
                src="<?= $me->basePath("vendor/dark_admin/img/avatar-3.jpg"); ?>" alt="..."
                class="img-fluid"-->
            <span class="img-fluid text-success"><i class="fa fa-user" style="font-size: 45px"></i></span>
            <div class="status online"></div>
        </div>
        <div class="content">
            <strong class="d-block">Nadia Halsey</strong>
            <span class="d-block">lorem ipsum dolor sit amit</span>
            <small class="date d-block">9:30am</small>
        </div>
    </a>
    <a href="#" class="dropdown-item message d-flex align-items-center">
        <div class="profile">
            <!--img
                src="<?= $me->basePath("vendor/dark_admin/img/avatar-2.jpg"); ?>" alt="..."
                class="img-fluid"-->
            <span class="img-fluid text-warning"><i class="fa fa-user" style="font-size: 45px"></i></span>
            <div class="status away"></div>
        </div>
        <div class="content">
            <strong class="d-block">Peter Ramsy</strong>
            <span class="d-block">lorem ipsum dolor sit amit</span>
            <small class="date d-block">7:40am</small>
        </div>
    </a>
    <a href="#" class="dropdown-item message d-flex align-items-center">
        <div class="profile">
            <!--img
                src="<?= $me->basePath("vendor/dark_admin/img/avatar-1.jpg"); ?>" alt="..."
                class="img-fluid"-->
            <span class="img-fluid text-danger"><i class="fa fa-user" style="font-size: 45px"></i></span>
            <div class="status busy"></div>
        </div>
        <div class="content">
            <strong class="d-block">Sam Kaheil</strong>
            <span
                class="d-block">lorem ipsum dolor sit amit</span>
            <small
                class="date d-block">6:55am</small>
        </div>
    </a>
    <a href="#" class="dropdown-item message d-flex align-items-center">
        <div class="profile">
            <!--img
                src="<?= $me->basePath("vendor/dark_admin/img/avatar-5.jpg"); ?>" alt="..."
                class="img-fluid"-->
            <span class="img-fluid text-grey"><i class="fa fa-user" style="font-size: 45px"></i></span>
            <div class="status offline"></div>
        </div>
        <div class="content">
            <strong class="d-block">Sara Wood</strong>
            <span
                class="d-block">lorem ipsum dolor sit amit</span>
            <small
                class="date d-block">10:30pm</small>
        </div>
    </a>
    <a href="#" class="dropdown-item text-center message">
        <strong>See All Messages <i class="fa fa-angle-right"></i></strong>
    </a>
</div>